name: Help and Support
markdown: redcarpet
pygments: true
permalink: /:categories/:title.html

# defaults
sass:
    syntax: scss        # scss|sass
    style:  compressed  # nested|expanded|compact|compressed
    
indextank_api_url: http://:penygamevusy@zuvuja.api.indexden.com
indextank_index: dev_help_pages