name: Help and Support
markdown: rdiscount
pygments: true
permalink: /:categories/:title.html

# defaults
sass:
    syntax: scss        # scss|sass
    style:  compressed  # nested|expanded|compact|compressed
elasticsearch_excludes: [index.html, 404.html, search.html, style.html, whatsnew.json]
