name: Help and Support
markdown: redcarpet
pygments: true
permalink: /:categories/:title.html

# defaults
sass:
    syntax: scss        # scss|sass
    style:  compressed  # nested|expanded|compact|compressed
indextank_excludes: [index.html, 404.html, search.html, style.html]